---
title: "BSMM-lab-1"
subtitle: "BSMM 8740 Fall 2023"
author: "Sophia-yi"
date: "September 18,2023"
format: html
editor: visual
self-contained: true
---

## Setup

Load packages and data:

```{r load-pkg-data}
#| message: false
library(Lahman)
```

## Exercises

### Exercise 1

```{r glimpse-data}
dplyr::glimpse(Teams)
```

The `Teams` dataset has \_\_\_ observations and \_\_\_ variables.

```{r}
dplyr::glimpse(Teams |> head() )
```

### Exercise 2

...

```{r}
library(magrittr)
mets <- Teams  |>
  dplyr::filter(teamID == "NYN")
my_mets <- mets |>
  dplyr::filter(yearID %in% 2004:2012)
my_mets |> 
  dplyr::select(teamID,yearID,W,L)
my_mets %>%
  dplyr::select(teamID,yearID,W,L) %>%
  dplyr::summarise(
    "2004-2012 wins"=sum(W)
    , "2004-2012 losses"=sum(L)
  )
```

### Exercise 3

...

```{r}
mets_ben <- Teams |>
  dplyr::select(yearID, teamID, G, W, L, RA, R) |>
  dplyr::filter(teamID == "NYN" & yearID %in% 2004:2012)
mets_ben
```

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(RS = R)    # new name = old name
mets_ben
  
```

### Exercise 4

...

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(WPct = W / (W + L))
mets_ben

```

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(W_hat = WPct * G)
mets_ben
```

### Exercise 5

...

```{r}
mets_ben %>%
  dplyr::summarise('better than expected'= sum(W>=W_hat)
                   , 'worse than expected'= sum(W<=W_hat)
  )
```

```{r}
Teams |>
  dplyr:: select(teamID, yearID,W,L,RS=R,RA) |>
  dplyr:: filter(teamID=="NYN") |>
  dplyr:: mutate(
    WPct = 1 / (1+(RA+RS)^2)
    , W_hat = WPct*(W+L)
  ) |>
  dplyr:: summarise(
    "better than expected"= sum(W>=W_hat)
    , "worse than expected"= sum(W<=W_hat)
  )
```

### Exercise 6

...

```{r}
mets_ben |> dplyr::arrange(desc(W))

```

### Exercise 7

...

```{r}
mets_ben %>% 
  dplyr::mutate(Diff = W - W_hat) |>
  dplyr::arrange(desc(Diff))
```

### Exercise 8

...

```{r}
mets_ben |>
  dplyr::summarize(
    num_years = nrow(mets_ben), 
    total_W = sum(W), 
    total_L = sum(L), 
    total_WPct = mean(WPct), 
    sum_resid = sum(WPct - W_hat)
  )
```

```{r}
total_wins <- sum(mets_ben$W)
total_losses <- sum(mets_ben$L)
overall_winning_percentage <- total_wins / (total_wins + total_losses)

cat("In these nine years, the Mets had a combined record of", total_wins, "wins and", total_losses, "losses, for an overall winning percentage of", overall_winning_percentage)

```

### Exercise 9

...

```         
```

```         
```

### Exercise 10

...

```{r}
mets_ben  |>
  dplyr::mutate(
    gm = ifelse(
      yearID==2004,
      'Jim',
      ifelse(
        yearID>=2011,
        'Sandy',
        'Omar')
      )
    )
```

### Exercise 11

```{r}
library(dplyr)
library(gt)
library(gtExtras)

mets_ben %>%
  group_by(gm) %>%
  summarise(
    num_years = n(),
    total_W = sum(W, na.rm = TRUE),
    total_L = sum(L, na.rm = TRUE),
    total_WPct = total_W / (total_W + total_L)
  ) %>%
  gt() %>%
  gt_theme_espn()

```

```         
```

```{r}

mets_ben_grouped <- mets_ben %>%
  group_by(gm) %>%
  summarize(
    num_years = n(),
    total_W = sum(W),
    total_L = sum(L),
    total_WPct = mean(WPct),
    sum_resid = sum(WPct - W_hat)
  )
print(mets_ben_grouped)
```

Lab 1

```{r}
library(Lahman)
dim(Teams)
```

```{r}
?Teams
```
